spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ssm?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  mvc:
    view:
      prefix: /WEB-INF/ #统一视图
      suffix: .jsp
    http:
      encoding:
        charset: UTF-8
        force: true
        enabled: true
    messages:
      encoding: UTF-8
server:
  tomcat:
    uri-encoding: utf-8
  port: 8070
mybatis:
  type-aliases-package: cn.itsource.ssm.domain,cn.itsource.ssm.query